[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_port = COM4
upload_speed = 115200
upload_command = $PYTHONEXE -m esptool --chip esp8266 --port $UPLOAD_PORT --baud $UPLOAD_SPEED --before default-reset --after hard-reset write-flash --flash-size detect 0x0 $SOURCE
lib_deps =
  knolleary/PubSubClient@^2.8
  tzapu/WiFiManager@^2.0.17
  plerup/EspSoftwareSerial@^8.2.0
build_flags =
  -D SERIAL_BAUD=115200
  -D STM32_UART_BAUD=57600
  -D STM32_RX_PIN=4
  -D STM32_TX_PIN=5
  -D STATUS_LED_PIN=2
  -D MQTT_HOST=\"broker.emqx.io\"
  -D MQTT_PORT=1883
  -D MQTT_TOPIC_ROOT=\"xiaohei/aquarium/khome-20260422\"
  -D AP_SSID=\"ESPXiaoHei\"
  -D AP_PASSWORD=\"sunjunjie@1\"
  -D HOME_WIFI_SSID=\"春风直达拉萨\"
  -D HOME_WIFI_PASSWORD=\"sunjunjie@1\"

monitor_filters = esp8266_exception_decoder
