[platformio]
build_dir = C:/pio_build/xiaohei_stm32

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
build_flags =
  -D SERIAL_BAUD=57600
  -D ESP_UART_BAUD=57600
  -D RELAY_ACTIVE_HIGH=1
  -D LIGHT_RELAY_PIN=PA2
  -D PUMP_RELAY_PIN=PA3
  -D MASTER_SWITCH_PIN=PA0
  -D LIGHT_BUTTON_PIN=PA1
  -D STATUS_LED_PIN=PC13
  -D INPUT_ACTIVE_LEVEL=LOW
  -D STATUS_LED_ACTIVE_LOW=1
