[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
build_flags =
  -D SERIAL_BAUD=115200
  -D RELAY_ACTIVE_HIGH=1
  -D RELAY_PIN=PB12
  -D BUTTON_PIN=PA0
  -D STATUS_LED_PIN=PC13
  -D BUTTON_ACTIVE_LEVEL=LOW
  -D STATUS_LED_ACTIVE_LOW=1

; 如果后续要烧录 STM32，可根据实际下载器打开或调整：
; upload_protocol = stlink
